/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LandingIndexImport } from './routes/landing/index'

// Create Virtual Routes

const MyScheduleIndexLazyImport = createFileRoute('/my-schedule/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyScheduleIndexLazyRoute = MyScheduleIndexLazyImport.update({
  id: '/my-schedule/',
  path: '/my-schedule/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/my-schedule/index.lazy').then((d) => d.Route),
)

const LandingIndexRoute = LandingIndexImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-schedule/': {
      id: '/my-schedule/'
      path: '/my-schedule'
      fullPath: '/my-schedule'
      preLoaderRoute: typeof MyScheduleIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingIndexRoute
  '/my-schedule': typeof MyScheduleIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingIndexRoute
  '/my-schedule': typeof MyScheduleIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/landing/': typeof LandingIndexRoute
  '/my-schedule/': typeof MyScheduleIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing' | '/my-schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing' | '/my-schedule'
  id: '__root__' | '/' | '/landing/' | '/my-schedule/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingIndexRoute: typeof LandingIndexRoute
  MyScheduleIndexLazyRoute: typeof MyScheduleIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingIndexRoute: LandingIndexRoute,
  MyScheduleIndexLazyRoute: MyScheduleIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/landing/",
        "/my-schedule/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/landing/": {
      "filePath": "landing/index.tsx"
    },
    "/my-schedule/": {
      "filePath": "my-schedule/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
