/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as IndexImport } from './routes/index'
import { Route as LandingIndexImport } from './routes/landing/index'
import { Route as DiscussionCreateIndexImport } from './routes/discussion/create/index'
import { Route as DiscussionInviteIdImport } from './routes/discussion/invite/$id'
import { Route as DiscussionEditIdImport } from './routes/discussion/edit/$id'
import { Route as DiscussionCreateIdImport } from './routes/discussion/create/$id'

// Create Virtual Routes

const MyCalendarIndexLazyImport = createFileRoute('/my-calendar/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const OauthRedirectIndexLazyImport = createFileRoute('/oauth/redirect/')()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyCalendarIndexLazyRoute = MyCalendarIndexLazyImport.update({
  id: '/my-calendar/',
  path: '/my-calendar/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/my-calendar/index.lazy').then((d) => d.Route),
)

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const LandingIndexRoute = LandingIndexImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRoute,
} as any)

const OauthRedirectIndexLazyRoute = OauthRedirectIndexLazyImport.update({
  id: '/oauth/redirect/',
  path: '/oauth/redirect/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/oauth.redirect/index.lazy').then((d) => d.Route),
)

const DiscussionCreateIndexRoute = DiscussionCreateIndexImport.update({
  id: '/discussion/create/',
  path: '/discussion/create/',
  getParentRoute: () => rootRoute,
} as any)

const DiscussionInviteIdRoute = DiscussionInviteIdImport.update({
  id: '/discussion/invite/$id',
  path: '/discussion/invite/$id',
  getParentRoute: () => rootRoute,
} as any)

const DiscussionEditIdRoute = DiscussionEditIdImport.update({
  id: '/discussion/edit/$id',
  path: '/discussion/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const DiscussionCreateIdRoute = DiscussionCreateIdImport.update({
  id: '/discussion/create/$id',
  path: '/discussion/create/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/my-calendar/': {
      id: '/my-calendar/'
      path: '/my-calendar'
      fullPath: '/my-calendar'
      preLoaderRoute: typeof MyCalendarIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/discussion/create/$id': {
      id: '/discussion/create/$id'
      path: '/discussion/create/$id'
      fullPath: '/discussion/create/$id'
      preLoaderRoute: typeof DiscussionCreateIdImport
      parentRoute: typeof rootRoute
    }
    '/discussion/edit/$id': {
      id: '/discussion/edit/$id'
      path: '/discussion/edit/$id'
      fullPath: '/discussion/edit/$id'
      preLoaderRoute: typeof DiscussionEditIdImport
      parentRoute: typeof rootRoute
    }
    '/discussion/invite/$id': {
      id: '/discussion/invite/$id'
      path: '/discussion/invite/$id'
      fullPath: '/discussion/invite/$id'
      preLoaderRoute: typeof DiscussionInviteIdImport
      parentRoute: typeof rootRoute
    }
    '/discussion/create/': {
      id: '/discussion/create/'
      path: '/discussion/create'
      fullPath: '/discussion/create'
      preLoaderRoute: typeof DiscussionCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/oauth/redirect/': {
      id: '/oauth/redirect/'
      path: '/oauth/redirect'
      fullPath: '/oauth/redirect'
      preLoaderRoute: typeof OauthRedirectIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof MainRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexLazyRoute
  '/my-calendar': typeof MyCalendarIndexLazyRoute
  '/discussion/create/$id': typeof DiscussionCreateIdRoute
  '/discussion/edit/$id': typeof DiscussionEditIdRoute
  '/discussion/invite/$id': typeof DiscussionInviteIdRoute
  '/discussion/create': typeof DiscussionCreateIndexRoute
  '/oauth/redirect': typeof OauthRedirectIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof MainRoute
  '/landing': typeof LandingIndexRoute
  '/login': typeof LoginIndexLazyRoute
  '/my-calendar': typeof MyCalendarIndexLazyRoute
  '/discussion/create/$id': typeof DiscussionCreateIdRoute
  '/discussion/edit/$id': typeof DiscussionEditIdRoute
  '/discussion/invite/$id': typeof DiscussionInviteIdRoute
  '/discussion/create': typeof DiscussionCreateIndexRoute
  '/oauth/redirect': typeof OauthRedirectIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_main': typeof MainRoute
  '/landing/': typeof LandingIndexRoute
  '/login/': typeof LoginIndexLazyRoute
  '/my-calendar/': typeof MyCalendarIndexLazyRoute
  '/discussion/create/$id': typeof DiscussionCreateIdRoute
  '/discussion/edit/$id': typeof DiscussionEditIdRoute
  '/discussion/invite/$id': typeof DiscussionInviteIdRoute
  '/discussion/create/': typeof DiscussionCreateIndexRoute
  '/oauth/redirect/': typeof OauthRedirectIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/landing'
    | '/login'
    | '/my-calendar'
    | '/discussion/create/$id'
    | '/discussion/edit/$id'
    | '/discussion/invite/$id'
    | '/discussion/create'
    | '/oauth/redirect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/landing'
    | '/login'
    | '/my-calendar'
    | '/discussion/create/$id'
    | '/discussion/edit/$id'
    | '/discussion/invite/$id'
    | '/discussion/create'
    | '/oauth/redirect'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/landing/'
    | '/login/'
    | '/my-calendar/'
    | '/discussion/create/$id'
    | '/discussion/edit/$id'
    | '/discussion/invite/$id'
    | '/discussion/create/'
    | '/oauth/redirect/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  MyCalendarIndexLazyRoute: typeof MyCalendarIndexLazyRoute
  DiscussionCreateIdRoute: typeof DiscussionCreateIdRoute
  DiscussionEditIdRoute: typeof DiscussionEditIdRoute
  DiscussionInviteIdRoute: typeof DiscussionInviteIdRoute
  DiscussionCreateIndexRoute: typeof DiscussionCreateIndexRoute
  OauthRedirectIndexLazyRoute: typeof OauthRedirectIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  LandingIndexRoute: LandingIndexRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  MyCalendarIndexLazyRoute: MyCalendarIndexLazyRoute,
  DiscussionCreateIdRoute: DiscussionCreateIdRoute,
  DiscussionEditIdRoute: DiscussionEditIdRoute,
  DiscussionInviteIdRoute: DiscussionInviteIdRoute,
  DiscussionCreateIndexRoute: DiscussionCreateIndexRoute,
  OauthRedirectIndexLazyRoute: OauthRedirectIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/landing/",
        "/login/",
        "/my-calendar/",
        "/discussion/create/$id",
        "/discussion/edit/$id",
        "/discussion/invite/$id",
        "/discussion/create/",
        "/oauth/redirect/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_main": {
      "filePath": "_main.tsx"
    },
    "/landing/": {
      "filePath": "landing/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/my-calendar/": {
      "filePath": "my-calendar/index.lazy.tsx"
    },
    "/discussion/create/$id": {
      "filePath": "discussion/create/$id.tsx"
    },
    "/discussion/edit/$id": {
      "filePath": "discussion/edit/$id.tsx"
    },
    "/discussion/invite/$id": {
      "filePath": "discussion/invite/$id.tsx"
    },
    "/discussion/create/": {
      "filePath": "discussion/create/index.tsx"
    },
    "/oauth/redirect/": {
      "filePath": "oauth.redirect/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
