import { fontFamilies, fontSize, fontWeights, letterSpacing, lineHeights, paragraphIndent, paragraphSpacing, textCase, textDecoration } from './typo';

export const font = {
  H1: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-0'],
    lineHeight: lineHeights['0'],
    fontSize: fontSize['6'],
    letterSpacing: letterSpacing['0'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  H2: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-0'],
    lineHeight: lineHeights['1'],
    fontSize: fontSize['5'],
    letterSpacing: letterSpacing['0'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  H3: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-1'],
    lineHeight: lineHeights['2'],
    fontSize: fontSize['4'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  T1: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-0'],
    lineHeight: lineHeights['3'],
    fontSize: fontSize['3'],
    letterSpacing: letterSpacing['0'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  T2: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-0'],
    lineHeight: lineHeights['4'],
    fontSize: fontSize['2'],
    letterSpacing: letterSpacing['0'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  T3: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-0'],
    lineHeight: lineHeights['5'],
    fontSize: fontSize['1'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B1 (M)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-2'],
    lineHeight: lineHeights['3'],
    fontSize: fontSize['3'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B2 (M)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-2'],
    lineHeight: lineHeights['6'],
    fontSize: fontSize['2'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B3 (M)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-2'],
    lineHeight: lineHeights['7'],
    fontSize: fontSize['1'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B1 (R)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-3'],
    lineHeight: lineHeights['3'],
    fontSize: fontSize['3'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B2 (R)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-3'],
    lineHeight: lineHeights['6'],
    fontSize: fontSize['2'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  'B3 (R)': {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-3'],
    lineHeight: lineHeights['7'],
    fontSize: fontSize['1'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
  caption: {
    fontFamily: fontFamilies['pretendard'],
    fontWeight: fontWeights['pretendard-2'],
    lineHeight: lineHeights['5'],
    fontSize: fontSize['0'],
    letterSpacing: letterSpacing['1'],
    paragraphSpacing: paragraphSpacing['0'],
    paragraphIndent: paragraphIndent['0'],
    textCase: textCase['none'],
    textDecoration: textDecoration['none'],
  },
};
