name: be-ci

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - "backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: |
          chmod +x gradlew
        shell: bash

      - name: Build gradle
        run: |
          ./gradlew clean build
        shell: bash

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/

      - name: Upload PR Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Backend CI',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion,
            });

