name: be-cd

on:
  push:
    branches:
      - dev
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Set up application.yml file
        working-directory: ./backend
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > src/main/resources/application-dev.yml
        shell: bash

      - name: Grant Execute Permission for gradlew
        working-directory: ./backend
        run: |
          chmod +x gradlew
        shell: bash

      - name: Build Backend
        working-directory: ./backend
        run: |
          ./gradlew clean build -Dspring.profiles.active=dev -x test

      # EC2로 파일 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/build/libs/*.jar"
          target: "~/app"

      # 배포 스크립트 실행
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            bash deploy_scripts/backend_deploy.sh
